'use strict';
const assert = require('assert');
const { REWARD_AT, REWARD_DAYS, daysEarned, applyCap } = require('./referral-rewards');
assert.strictEqual(REWARD_AT, 3); assert.strictEqual(REWARD_DAYS, 7);
assert.strictEqual(daysEarned(0, 1), 0, 'one install pays nothing');
assert.strictEqual(daysEarned(0, 2), 0, 'two installs pay nothing');
assert.strictEqual(daysEarned(0, 3), 7, 'three installs pay seven days');
assert.strictEqual(daysEarned(2, 1), 7, 'the third install crosses the line');
assert.strictEqual(daysEarned(3, 1), 0, 'a fourth pays nothing more');
assert.strictEqual(daysEarned(0, 6), 7, 'six at once still pay once');
assert.strictEqual(daysEarned(2, 1, true), 0, 'never paid twice');
assert.strictEqual(daysEarned(0, 0), 0);
assert.deepStrictEqual(applyCap(7, 0).grant, 7);
assert.strictEqual(applyCap(7, 14).grant, 0, 'the 30-day cap holds');
console.log(`referral-rewards smoke: PASS — nothing below ${REWARD_AT}, ${REWARD_DAYS} days once at ${REWARD_AT}, never twice`);
