'use strict';
const assert = require('assert');
const { reconcile } = require('./referral-reconcile');
const R = 'referrer';
const row = (id, counted = null) => ({ referred_id: id, counted_at: counted });
let d = reconcile({ referrerId: R, referrals: [row('a'), row('b')], priorCounted: 0, alreadyRewarded: false, grantedInWindow: 0 });
assert.strictEqual(d.days, 0); assert.strictEqual(d.reason, 'below_threshold'); assert.strictEqual(d.eligible.length, 2);
d = reconcile({ referrerId: R, referrals: [row('a'), row('b'), row('c')], priorCounted: 0, alreadyRewarded: false, grantedInWindow: 0 });
assert.strictEqual(d.days, 7); assert.strictEqual(d.reason, 'granted'); assert.strictEqual(d.countedAfter, 3);
d = reconcile({ referrerId: R, referrals: [row('a', 'x'), row('b', 'x'), row('c')], priorCounted: 2, alreadyRewarded: false, grantedInWindow: 0 });
assert.strictEqual(d.days, 7, 'the third install, arriving later, pays');
d = reconcile({ referrerId: R, referrals: [row('a', 'x'), row('b', 'x'), row('c', 'x'), row('d')], priorCounted: 3, alreadyRewarded: true, grantedInWindow: 7 });
assert.strictEqual(d.days, 0); assert.strictEqual(d.reason, 'already_rewarded');
d = reconcile({ referrerId: R, referrals: [row(R), row('a'), row('b')], priorCounted: 0, alreadyRewarded: false, grantedInWindow: 0 });
assert.strictEqual(d.days, 0); assert.strictEqual(d.rejected[0].reason, 'self_referral'); assert.strictEqual(d.eligible.length, 2);
d = reconcile({ referrerId: R, referrals: [], priorCounted: 0, alreadyRewarded: false, grantedInWindow: 0 });
assert.strictEqual(d.days, 0); assert.strictEqual(d.reason, 'nothing_new');
console.log('referral-reconcile smoke: PASS — installs count, renders and flags do not; seven days once at three, self never');
